{
 "title": "Balancer_Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Token List of Balancer",
   "type": "text",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "Tokens :\n<br>\n<br>\n<br>\n<ul>\n  <li> yearn.finance</li>\n  <li> Uniswap </li>\n  <li> SushiToken </li>\n  <li> Aave Tokens </li>\n  <li> Balancer </li>\n  <li> Compund </li>\n  <li> Wrapped Ether </li>\n</ul>\n\n</ul>"
   },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "queryText": "query {\n      data:submissions(user:\"$user\"){\n          Time:submitTime\n          idle running completed\n      }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Balancer Strategy Type",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "expr": "query_balancers_pools_strategyType",
     "legendFormat": "Strategy Type",
     "queryText": "query {\n      data:submissions(user:\"$user\"){\n          Time:submitTime\n          idle running completed\n      }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Total Weight",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "expr": "query_balancers_pools_totalWeight",
     "queryText": "query {\n      data:submissions(user:\"$user\"){\n          Time:submitTime\n          idle running completed\n      }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Balancer total liquidity",
   "type": "graph",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "expr": "query_balancers_totalLiquidity",
     "legendFormat": "Total Liquidity",
     "queryText": "query {\n      data:submissions(user:\"$user\"){\n          Time:submitTime\n          idle running completed\n      }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Total Shares",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "expr": "query_balancers_pools_totalShares",
     "queryText": "query {\n      data:submissions(user:\"$user\"){\n          Time:submitTime\n          idle running completed\n      }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Balancer Total Swap Fee",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "expr": "query_balancers_totalSwapFee",
     "legendFormat": "Total Swap Fee",
     "queryText": "query {\n      data:submissions(user:\"$user\"){\n          Time:submitTime\n          idle running completed\n      }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Panel Balancer Total Swap Volume",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 13, "x": 11, "y": 12 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "expr": "query_balancers_totalSwapVolume ",
     "legendFormat": "Total Swap Volume",
     "queryText": "query {\n      data:submissions(user:\"$user\"){\n          Time:submitTime\n          idle running completed\n      }\n}",
     "timePath": "Time"
    }
   ]
  }
 ]
}