{
 "title": "Uniswap V3 Tokens Statistics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Uniswap V3",
   "type": "text",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "\nToken0  : Binance USD \n<br>\n\n\nSymbol: BUSD\n\n<br> <br>\nToken0 : Wrapped Ether\n<br>\nSymbol: WETH\n\n"
   },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "expr": "query_pools_token1_name{}",
     "queryText": "query {\n      data:submissions(user:\"$user\"){\n          Time:submitTime\n          idle running completed\n      }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "BUSD_TotalSupply",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "expr": "query_pools_token0_totalSupply",
     "legendFormat": "BUSD Total Supply",
     "queryText": "query {\n      data:submissions(user:\"$user\"){\n          Time:submitTime\n          idle running completed\n      }\n}",
     "timePath": "Time"
    },
    { "expr": "query_pools_token1_totalSupply", "legendFormat": "wETH Total Supply" }
   ]
  },
  {
   "title": "Total supply of wEth",
   "type": "stat",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "expr": "query_pools_token0_derivedETH",
     "legendFormat": "BinanceUSD_ DerievedETH",
     "queryText": "query {\n      data:submissions(user:\"$user\"){\n          Time:submitTime\n          idle running completed\n      }\n}",
     "timePath": "Time"
    },
    { "expr": "query_pools_token1_derivedETH", "legendFormat": "WrappedEth_Derieved ETH" }
   ]
  },
  {
   "title": "Binance Price USD_Token0",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "query_pools_token0_feesUSD{}", "legendFormat": "Binance _price_USD" }
   ]
  },
  {
   "title": "WrappedEtherPrice in USD_Token1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "expr": "query_pools_token1_feesUSD{}",
     "legendFormat": "wEth",
     "queryText": "query {\n      data:submissions(user:\"$user\"){\n          Time:submitTime\n          idle running completed\n      }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Volume of Binance in USD _ token0",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "expr": "query_pools_token0_volumeUSD",
     "legendFormat": "volume_BUSD",
     "queryText": "query {\n      data:submissions(user:\"$user\"){\n          Time:submitTime\n          idle running completed\n      }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "wEth Volume in USD",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "expr": "query_pools_token1_volumeUSD ",
     "legendFormat": "wETH_VolumeUSD",
     "queryText": "query {\n      data:submissions(user:\"$user\"){\n          Time:submitTime\n          idle running completed\n      }\n}",
     "timePath": "Time"
    }
   ]
  }
 ]
}