{
 "title": "Uniswapv3_Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Liquidity of Uniswap v3 Pool",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "expr": "query_pools_liquidity",
     "legendFormat": "liquidity",
     "queryText": "query {\n      data:submissions(user:\"$user\"){\n          Time:submitTime\n          idle running completed\n      }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Uniswap V3 stats",
   "type": "graph",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "expr": "query_pools_sqrtPrice",
     "legendFormat": "Sqrt Price",
     "queryText": "query {\n      data:submissions(user:\"$user\"){\n          Time:submitTime\n          idle running completed\n      }\n}",
     "timePath": "Time"
    },
    { "expr": "query_pools_tick", "legendFormat": "Tick value" }
   ]
  },
  {
   "title": "Uniswap V3 Volume  in USD",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "expr": "query_pools_volumeUSD",
     "legendFormat": "Volumne in USD",
     "queryText": "query {\n      data:submissions(user:\"$user\"){\n          Time:submitTime\n          idle running completed\n      }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Uniswap V3 Locked values",
   "type": "stat",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "expr": "query_pools_totalValueLockedETH ",
     "legendFormat": "Total Value Locked ETH",
     "queryText": "query {\n      data:submissions(user:\"$user\"){\n          Time:submitTime\n          idle running completed\n      }\n}",
     "timePath": "Time"
    },
    {
     "expr": "query_pools_totalValueLockedUSD",
     "legendFormat": "Total Value Locked USD"
    }
   ]
  }
 ]
}